# main configuration file for the framework.
cameraConfig:
  pos: [0.0,0.0,0.0]
  look_at: [0.0,1.0,0.0]
  fov: 60.0
  clear_color: [0.5,0.5,0.5,1.0]

simulationLog:
  # main log for the entire framework.
  outfile: run/SimulationLog.txt
  mode: a
