# main configuration file for the framework.
cameraConfig:
  pos: [0.0,0.0,0.0]
  lookAt: [0.0,1.0,0.0]
  fov: 60.0

simulationLog:
  # main log for the entire framework.
  outfile: run/SimulationLog.txt
  mode: a
