# Directly specify hooks in the World object (METHODS) for keys,
# these keys should not be overidden by Elements
global_keys:
  - key: control-v
    callback: toggleVerbose
    comment: Toggles verbose mode
  - key: control-q
    callback: quit
    comment: Quit the experiment
#  - key: escape
#    callback: advanceFSM
#    comment: Advance State Machine
#    args: ["auto"]
  - key: control-m
    callback: toggleMouseCursor
    comment: Show/Hide mouse cursor
#  - key: control-g
#    callback: advanceFSM
#    comment: Advance State Machine
#    args: ["exitPilot"]
